<center><h1>Deep Learning</h1></center>

- Single layer perceptron, no hidden layer, Linear classifier
- There are many disadvantages to Single layer perceptron so we use Multi Layer Perceptron, as it consists atleast one hidden layer
- CNN is used for images 
- RNN is used for sequential data
- RBM: Restricted Boltzmann Machine?
- Deep Neural Networks are used for classification type models 

<h2>Artificial Neural Networks</h2>

- x1,x2,x3,....,xn are inputs
- w1,w2,w3,....,wn are weights
- weights are different amounts of effect each type of input has on the input
- Bias is calculated by S = ΣXiWi same as Linear Regression
- Check out principle of least squares
- Activation of bias is done by using sigmoid function 
- Summation => Addition of bias if any => Sigmoid function => output is the output of the layer
- After getting the output of activation or Transfer function, We again apply the weights and appropriate bias and then sigmoid function to get the output of Forward propagation y1 and y2
- Next step is backward propagation 
    1) Compare the output to original given values 
    2) If it is same, we can stop at this step
    3) If it is not, then we use the output to update the weights which can take upto 1 hour
    4) To update the weights, we use something called gradient descent, similar to slope
    5) During backward propagation, our aim is to update the values of each of the weights
    6) If there is any change in the weights, we apply forward propagation again
    7) Steps are repeated
- Gradient Desent
    - We take total error by mean square method value summation 
    - We take Derivative of (Etotal / W5) to get the slope of that, to apply in the formula:
        - New Weight = Old Weight - Assumed eeta value * Slope (for example Etotal/W5)
    - Etotal/W5, applying chain rule as W5 is dependent on output of output of y2, y2(summation) and hence H1
    - Same process is extended till we get input 
        - Etotal/w1 = e1/out h1 + e2/out h2
        - e1 depends on y1, e2 depends on h2
        - y1 depends on y output (backward equation)
    - Then, as continued we apply forward propagation and repeat the cycle till we get the correct output
- Each Hidden layer, we apply the same process again and again until the output is similar to correct value.
- Look out for Artificial Neural Network Problems in youtube
- Vanishing Gradient:
    - As we do multiple iterations, gradient could get reduced to 0
- Exploding Gradient: 
    - As we do multiple iterations, gradient could explode into higher values
- We have to use multiple methods to get control these effects
- Activiation function in Artificial Neural Networks is sigmoid function 

<h3> Activation Functions </h3>

- Linear function / Identity function 
    - Backward propagation not possible
- Step Function 
- Sigmoid function 
- Hyperbolic Tangent Function 
- Rectified Linear Unit Function (ReLu)
    - max(0,x), less than 0 means 0, more than x means x itself 
- Softmax Activation Function 
    - Can only be used when there are multiple inputs


In [1]:
import numpy as np 
input_array = np.array([[1,0,1],[1,1,1],[0,1,0],[0,1,1]])
output_array = np.array([[1],[1],[0],[0]])
print(input_array)
print(output_array)


[[1 0 1]
 [1 1 1]
 [0 1 0]
 [0 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [2]:
np.random.seed(10)
weights = np.random.random([3,1])
print(weights)

[[0.77132064]
 [0.02075195]
 [0.63364823]]


In [3]:
sum_bias = 0.02 + np.dot(input_array,weights)
def activation(x):
    return 1/(1+ np.exp(-x))
predicted_output = activation(sum_bias)
print(predicted_output)
error = output_array - predicted_output
print(error)

[[0.8061162 ]
 [0.80933899]
 [0.51018658]
 [0.66248773]]
[[ 0.1938838 ]
 [ 0.19066101]
 [-0.51018658]
 [-0.66248773]]
